"use client";

/**
 * app/global-error.tsx
 *
 * Catches errors thrown in the root layout itself — a narrower scope than
 * app/error.tsx which handles route-segment errors. Required by Next.js 14
 * to prevent the entire app from going blank when the root layout errors.
 *
 * This file was generated by the Sentry wizard and extended with SaveQuest
 * branding. It must use <html> and <body> tags because it replaces the
 * root layout entirely when rendered.
 *
 * Sentry captures the exception automatically via the ErrorBoundary wrapper.
 */

import * as Sentry from "@sentry/nextjs";
import NextError from "next/error";
import { useEffect } from "react";

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    Sentry.captureException(error);
  }, [error]);

  return (
    <html lang="en" className="dark">
      <body style={{ margin: 0, background: "#0f0f14" }}>
        <div
          style={{
            minHeight: "100vh",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            padding: "1rem",
            textAlign: "center",
            fontFamily: "system-ui, sans-serif",
            color: "white",
          }}
        >
          <div style={{ fontSize: "3.5rem", marginBottom: "1rem" }}>⚡</div>
          <h1
            style={{
              fontSize: "1.5rem",
              fontWeight: "bold",
              marginBottom: "0.5rem",
            }}
          >
            SaveQuest hit a snag
          </h1>
          <p
            style={{
              color: "rgba(255,255,255,0.5)",
              fontSize: "0.875rem",
              marginBottom: "1.5rem",
              maxWidth: "320px",
            }}
          >
            Something went wrong at the application level. Your progress is
            safe — please try refreshing.
          </p>
          <button
            onClick={reset}
            style={{
              background: "#635bff",
              color: "white",
              border: "none",
              borderRadius: "0.75rem",
              padding: "0.75rem 1.5rem",
              fontSize: "0.875rem",
              fontWeight: "600",
              cursor: "pointer",
            }}
          >
            Try again
          </button>
        </div>
      </body>
    </html>
  );
}
